# Generated by Django 3.1.5 on 2021-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='수량'),
            preserve_default=False,
        ),
    ]
