# Generated by Django 3.1.5 on 2021-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='대기중', max_length=32, verbose_name='상태'),
        ),
    ]
